/* gen.cpp */

#include "gen.hpp"
#include <sstream>
#include <algorithm>


void AsmGenerator::Generate(const std::string& filename)
{
	std::ofstream fout(filename);
	if (!fout.is_open())
	{
		std::cerr << "Cannot open output file " << filename << std::endl;
		return;
	}
	out = &fout;

	*out << ".386\n";
	*out << ".model flat, stdcall\n";
	*out << "option casemap:none\n";
	*out << "includelib kernel32.lib\n";
	*out << "extern ExitProcess@4 : proc\n\n";

	*out << "; Assembly generated by compiler\n\n";

	GenerateDataSegment();

	*out << "_TEXT SEGMENT\n\n";

	const auto& triads = triadGen->GetTriads();
	const auto& funcs = triadGen->GetFunctions();

	for (size_t i = 0; i < funcs.size(); ++i)
	{
		int start = funcs[i].start;
		int end = funcs[i].end;
		if (start < 0 || end < 0) continue;
		if (triads[start].op == "proc")
		{
			if (triads[start].op == "proc")
			{
				std::string funcName = triads[start].arg1;
				Symbol* funcSym = tree->FindSymbol(funcName);
				if (funcName == "main" && funcSym)
					mainAsmName = funcSym->asmName;

				int frameSize = funcSym ? funcSym->frameSize : 0;
				GenerateFunction(start, end, funcName, frameSize);
			}
		}
	}

	if (!mainAsmName.empty())
	{
		*out << "_start PROC\n";
		*out << "\tcall " << mainAsmName << "\n";
		*out << "\tpush 0\n";
		*out << "\tcall ExitProcess@4\n";
		*out << "_start ENDP\n\n";
	}
	else
	{
		return;
	}

	*out << "_TEXT ENDS\n";
	*out << "END\n";
	fout.close();
	std::cout << "Assembly code written to " << filename << std::endl;
}

void AsmGenerator::GenerateDataSegment()
{
	*out << "_BSS SEGMENT\n";
	if (tree->GetScopes().empty()) return;
	const auto& globalScope = tree->GetScopes()[0];
	for (const auto& pair : globalScope)
	{
		const Symbol& sym = pair.second;
		if (sym.kind == OBJECT_FUNCTION) continue;
		std::string asmName = sym.asmName;
		int elemSize = Tree::TypeSize(sym.type);
		int count = (sym.arraySize > 0) ? sym.arraySize : 1;
		int totalSize = elemSize * count;

		std::string dupType;
		switch (elemSize)
		{
		case 1: dupType = "DB"; break;
		case 2: dupType = "DW"; break;
		case 4: dupType = "DD"; break;
		case 8: dupType = "DQ"; break;
		default: dupType = "DD";
		}
		*out << "\tPUBLIC " << asmName << "\n";
		*out << asmName << " " << dupType << " " << std::hex << totalSize << "H DUP (?)\n";
		*out << std::dec;
	}
	*out << "_BSS ENDS\n\n";
}

void AsmGenerator::GenerateFunction(int funcStart, int funcEnd, const std::string& funcName, int frameSize)
{
	const auto& triads = triadGen->GetTriads();
	indexTriads.clear();
	tempOffsets.clear();

	std::set<int> usedTriads;
	for (int i = funcStart; i < funcEnd; ++i)
	{
		const auto& t = triads[i];
		auto check = [&](const std::string& arg)
			{
				int idx = ParseIndex(arg);
				if (idx >= 0) usedTriads.insert(idx);
			};
		check(t.arg1);
		check(t.arg2);
	}
	int tempBase = -frameSize - 4;
	for (int idx : usedTriads)
	{
		if (idx < funcStart || idx >= funcEnd) continue;
		if (triads[idx].op == "deleted" || triads[idx].op == "nop") continue;
		tempOffsets[idx] = tempBase;
		tempBase -= 4;
	}
	int totalFrame = -tempBase;

	std::set<int> jumpTargets;
	for (int i = funcStart; i < funcEnd; ++i)
	{
		const auto& t = triads[i];
		if (t.op == "goto")
		{
			int target = ParseIndex(t.arg1);
			if (target >= 0) jumpTargets.insert(target);
		}
		else if (t.op == "if")
		{
			int target = ParseIndex(t.arg2);
			if (target >= 0) jumpTargets.insert(target);
		}
	}

	Symbol* funcSym = tree->FindSymbol(funcName);
	std::string asmFuncName = funcSym ? funcSym->asmName : funcName;
	*out << asmFuncName << " PROC\n";
	*out << "\tpush ebp\n";
	*out << "\tmov ebp, esp\n";
	if (totalFrame > 0)
		*out << "\tsub esp, " << totalFrame << "\n";

	for (int i = funcStart; i < funcEnd; ++i)
	{
		if (jumpTargets.count(i))
			*out << "@@L" << i << ":\n";

		const auto& t = triads[i];
		if (t.op == "deleted" || t.op == "nop") continue;
		if (t.op == "proc" || t.op == "prolog" || t.op == "epilog" || t.op == "ret" || t.op == "endp")
			continue;

		if (t.op == "=")
		{
			LoadToEAX(t.arg2);
			StoreFromEAX(t.arg1);
		}
		else if (t.op == "+" || t.op == "-" || t.op == "*" || t.op == "/" || t.op == "%" ||
			t.op == "<" || t.op == "<=" || t.op == ">" || t.op == ">=" || t.op == "==" || t.op == "!=")
		{
			LoadToEAX(t.arg1);
			*out << "\tpush eax\n";
			LoadToEAX(t.arg2);
			*out << "\tmov ebx, eax\n";
			*out << "\tpop eax\n";
			if (t.op == "+") *out << "\tadd eax, ebx\n";
			else if (t.op == "-") *out << "\tsub eax, ebx\n";
			else if (t.op == "*") *out << "\timul eax, ebx\n";
			else if (t.op == "/")
			{
				*out << "\tcdq\n";
				*out << "\tidiv ebx\n";
			}
			else if (t.op == "%")
			{
				*out << "\tcdq\n";
				*out << "\tidiv ebx\n";
				*out << "\tmov eax, edx\n";
			}
			else if (t.op == "<") { *out << "\tcmp eax, ebx\n"; *out << "\tsetl al\n"; *out << "\tmovzx eax, al\n"; }
			else if (t.op == "<=") { *out << "\tcmp eax, ebx\n"; *out << "\tsetle al\n"; *out << "\tmovzx eax, al\n"; }
			else if (t.op == ">") { *out << "\tcmp eax, ebx\n"; *out << "\tsetg al\n"; *out << "\tmovzx eax, al\n"; }
			else if (t.op == ">=") { *out << "\tcmp eax, ebx\n"; *out << "\tsetge al\n"; *out << "\tmovzx eax, al\n"; }
			else if (t.op == "==") { *out << "\tcmp eax, ebx\n"; *out << "\tsete al\n"; *out << "\tmovzx eax, al\n"; }
			else if (t.op == "!=") { *out << "\tcmp eax, ebx\n"; *out << "\tsetne al\n"; *out << "\tmovzx eax, al\n"; }

			if (tempOffsets.count(i))
				*out << "\tmov [ebp" << tempOffsets[i] << "], eax\n";
		}
		else if (t.op == "-" && t.arg2.empty())
		{
			LoadToEAX(t.arg1);
			*out << "\tneg eax\n";
			if (tempOffsets.count(i))
				*out << "\tmov [ebp" << tempOffsets[i] << "], eax\n";
		}
		else if (t.op == "cast")
		{
			LoadToEAX(t.arg2);
			if (tempOffsets.count(i))
				*out << "\tmov [ebp" << tempOffsets[i] << "], eax\n";
		}
		else if (t.op == "if")
		{
			LoadToEAX(t.arg1);
			*out << "\tcmp eax, 0\n";
			*out << "\tje @@L" << t.arg2 << "\n";
		}
		else if (t.op == "goto")
		{
			*out << "\tjmp @@L" << t.arg1 << "\n";
		}
		else if (t.op == "call")
		{
			Symbol* callee = tree->FindSymbolByAsmName(t.arg1);
			if (callee)
			{
				*out << "\tcall " << callee->asmName << "\n";
				if (tempOffsets.count(i))
					*out << "\tmov [ebp" << tempOffsets[i] << "], eax\n";
			}
		}
		else if (t.op == "index")
		{
			Symbol* arrSym = tree->FindSymbolByAsmName(t.arg1);
			int elemSize = arrSym ? Tree::TypeSize(arrSym->type) : 4;
			LoadEffectiveAddress(t.arg1);
			*out << "\tpush eax\n";
			LoadToEAX(t.arg2);
			*out << "\tmov ebx, " << elemSize << "\n";
			*out << "\timul eax, ebx\n";
			*out << "\tpop ebx\n";
			*out << "\tadd eax, ebx\n";
			indexTriads.insert(i);
			if (tempOffsets.count(i))
				*out << "\tmov [ebp" << tempOffsets[i] << "], eax\n";
		}
		else
		{

		}
	}

	*out << "\tmov esp, ebp\n";
	*out << "\tpop ebp\n";
	*out << "\tret\n";
	*out << asmFuncName << " ENDP\n\n";
}

int AsmGenerator::ParseIndex(const std::string& s)
{
	if (s.size() >= 3 && s.front() == '(' && s.back() == ')')
	{
		try { return std::stoi(s.substr(1, s.size() - 2)); }
		catch (...) { return -1; }
	}
	return -1;
}

bool AsmGenerator::IsTempIndex(const std::string& operand, int& idx)
{
	idx = ParseIndex(operand);
	return idx >= 0;
}

std::string AsmGenerator::OperandToStr(const std::string& op, bool asAddress)
{
	int idx;
	if (IsTempIndex(op, idx))
	{
		auto it = tempOffsets.find(idx);
		if (it != tempOffsets.end())
		{
			std::stringstream ss;
			ss << "[ebp" << it->second << "]";
			return ss.str();
		}
		return "???";
	}
	char* end;
	long val = strtol(op.c_str(), &end, 10);
	if (*end == '\0')
	{
		return op;
	}
	Symbol* sym = tree->FindSymbolByAsmName(op);
	if (sym)
	{
		std::stringstream ss;
		if (sym->isLocal)
			ss << "[ebp" << sym->offset << "]";
		else
			return sym->asmName;
	}
	return op;
}

void AsmGenerator::LoadToEAX(const std::string& operand)
{
	int idx;
	if (IsTempIndex(operand, idx) && indexTriads.count(idx))
	{
		// это ссылка на элемент массива, нужно разыменовать
		std::string addr = OperandToStr(operand, true);
		*out << "\tmov ebx, " << addr << "\n";
		*out << "\tmov eax, [ebx]\n";
	}
	else
	{
		std::string opStr = OperandToStr(operand);
		// если immediate
		if (opStr.find('[') == std::string::npos && opStr.find("ebp") == std::string::npos)
		{
			// либо число, либо глобальная переменная
			char* end;
			strtol(opStr.c_str(), &end, 10);
			if (*end == '\0')
			{
				*out << "\tmov eax, " << opStr << "\n";
			}
			else
			{
				*out << "\tmov eax, " << opStr << "\n"; // глобальная переменная
			}
		}
		else
		{
			*out << "\tmov eax, " << opStr << "\n";
		}
	}
}

void AsmGenerator::StoreFromEAX(const std::string& operand)
{
	int idx;
	if (IsTempIndex(operand, idx) && indexTriads.count(idx))
	{
		// присваивание в элемент массива
		std::string addr = OperandToStr(operand, true);
		*out << "\tmov ebx, " << addr << "\n";
		*out << "\tmov [ebx], eax\n";
	}
	else
	{
		std::string opStr = OperandToStr(operand);
		*out << "\tmov " << opStr << ", eax\n";
	}
}

void AsmGenerator::LoadEffectiveAddress(const std::string& operand)
{
	Symbol* sym = tree->FindSymbolByAsmName(operand);
	if (sym && sym->isLocal)
	{
		*out << "\tlea eax, [ebp" << sym->offset << "]\n";
	}
	else if (sym)
	{
		*out << "\tmov eax, OFFSET " << sym->asmName << "\n";
	}
	else
	{
		*out << "\tmov eax, " << operand << " ; ???\n";
	}
}