/* gen.cpp */

#include "gen.hpp"
#include <sstream>
#include <algorithm>
#include <cstdlib>
#include <iomanip>

void AsmGenerator::Generate(const std::string& filename)
{
	std::ofstream fout(filename);
	if (!fout.is_open())
	{
		std::cerr << "Cannot open output file " << filename << std::endl;
		return;
	}
	out = &fout;

	*out << "option casemap:none\n";
	*out << "includelib kernel32.lib\n";
	*out << "extern ExitProcess : proc\n\n";

	*out << "; Assembly generated by compiler (x64)\n\n";

	GenerateDataSegment();
	GenerateDataSegmentInit();

	*out << "_TEXT SEGMENT\n\n";

	const auto& triads = triadGen->GetTriads();
	const auto& funcs = triadGen->GetFunctions();

	for (size_t i = 0; i < funcs.size(); ++i)
	{
		int start = funcs[i].start;
		int end = funcs[i].end;
		if (start < 0 || end < 0) continue;
		if (triads[start].op == "proc")
		{
			std::string funcName = triads[start].arg1;
			Symbol* funcSym = tree->FindSymbol(funcName);
			if (funcName == "main" && funcSym)
				mainAsmName = funcSym->asmName;

			int frameSize = funcSym ? funcSym->frameSize : 0;
			GenerateFunction(start, end, funcName, frameSize);
		}
	}

	if (!mainAsmName.empty())
	{
		*out << "_start PROC\n";
		*out << "\tsub rsp, 28h\n";
		*out << "\tcall " << mainAsmName << "\n";
		*out << "\tmov ecx, eax\n";
		*out << "\tcall ExitProcess\n";
		*out << "_start ENDP\n\n";
	}
	else
	{
		if (scanner)
			scanner->PrintWarning("No 'main' function found, _start not generated");
	}

	*out << "_TEXT ENDS\n";
	*out << "END _start\n";
	fout.close();
	std::cout << "Assembly code written to " << filename << std::endl;
}

void AsmGenerator::GenerateDataSegment()
{
	*out << "_BSS SEGMENT\n";
	if (tree->GetScopes().empty()) return;
	const auto& globalScope = tree->GetScopes()[0];
	for (const auto& pair : globalScope)
	{
		const Symbol& sym = pair.second;
		if (sym.kind == OBJECT_FUNCTION) continue;
		if (!sym.initValue.empty()) continue;

		std::string asmName = sym.asmName;
		int elemSize = Tree::TypeSize(sym.type);
		int totalElements = (sym.arraySize > 0) ? sym.arraySize : 1;

		std::string dupType;
		switch (elemSize)
		{
		case 1: dupType = "DB"; break;
		case 2: dupType = "DW"; break;
		case 4: dupType = "DD"; break;
		case 8: dupType = "DQ"; break;
		default: dupType = "DD";
		}
		*out << "\tPUBLIC " << asmName << "\n";
		*out << asmName << " " << dupType << " " << std::hex << totalElements << "H DUP (?)\n";
		*out << std::dec;
	}
	*out << "_BSS ENDS\n\n";
}

void AsmGenerator::GenerateDataSegmentInit()
{
	const auto& globalScope = tree->GetScopes()[0];
	bool hasData = false;
	for (const auto& pair : globalScope)
	{
		const Symbol& sym = pair.second;
		if (sym.initValue.empty()) continue;
		if (!hasData)
		{
			*out << "_DATA SEGMENT\n";
			hasData = true;
		}
		std::string asmName = sym.asmName;
		int elemSize = Tree::TypeSize(sym.type);
		std::string dupType;
		switch (elemSize)
		{
		case 1: dupType = "DB"; break;
		case 2: dupType = "DW"; break;
		case 4: dupType = "DD"; break;
		case 8: dupType = "DQ"; break;
		default: dupType = "DD";
		}
		*out << "\t" << asmName << " " << dupType << " " << sym.initValue << "\n";
	}
	if (hasData) *out << "_DATA ENDS\n\n";
}

void AsmGenerator::GenerateFunction(int funcStart, int funcEnd, const std::string& funcName, int frameSize)
{
	const auto& triads = triadGen->GetTriads();
	indexTriads.clear();
	tempOffsets.clear();

	std::set<int> usedTriads;
	for (int i = funcStart; i < funcEnd; ++i)
	{
		const auto& t = triads[i];
		auto check = [&](const std::string& arg)
			{
				int idx = ParseIndex(arg);
				if (idx >= 0) usedTriads.insert(idx);
			};
		check(t.arg1);
		check(t.arg2);
	}

	int alignedFrame = (frameSize + 15) & ~15;
	int tempBase = -alignedFrame - 8;
	for (int idx : usedTriads)
	{
		if (idx < funcStart || idx >= funcEnd) continue;
		if (triads[idx].op == "deleted" || triads[idx].op == "nop") continue;
		tempOffsets[idx] = tempBase;
		tempBase -= 8;
	}
	int totalFrame = -tempBase;
	totalFrame = (totalFrame + 15) & ~15;

	std::set<int> jumpTargets;
	for (int i = funcStart; i < funcEnd; ++i)
	{
		const auto& t = triads[i];
		if (t.op == "goto")
		{
			int target = ParseIndex(t.arg1);
			if (target >= 0) jumpTargets.insert(target);
		}
		else if (t.op == "if")
		{
			int target = ParseIndex(t.arg2);
			if (target >= 0) jumpTargets.insert(target);
		}
	}

	Symbol* funcSym = tree->FindSymbol(funcName);
	std::string asmFuncName = funcSym ? funcSym->asmName : funcName;
	*out << asmFuncName << " PROC\n";
	*out << "\tpush rbp\n";
	*out << "\tmov rbp, rsp\n";
	if (totalFrame > 0)
		*out << "\tsub rsp, " << totalFrame << "\n";

	for (int i = funcStart; i < funcEnd; ++i)
	{
		if (jumpTargets.count(i))
			*out << "@@L" << i << ":\n";

		const auto& t = triads[i];
		if (t.op == "deleted" || t.op == "nop") continue;
		if (t.op == "proc" || t.op == "prolog" || t.op == "epilog" || t.op == "ret" || t.op == "endp")
			continue;

		if (t.op == "=")
		{
			LoadToRAX(t.arg2);
			StoreFromRAX(t.arg1);
		}
		else if (t.op == "+" || t.op == "-" || t.op == "*" || t.op == "/" || t.op == "%" ||
			t.op == "<" || t.op == "<=" || t.op == ">" || t.op == ">=" || t.op == "==" || t.op == "!=")
		{
			LoadToRAX(t.arg1);
			*out << "\tpush rax\n";
			LoadToRAX(t.arg2);
			*out << "\tmov rbx, rax\n";
			*out << "\tpop rax\n";
			if (t.op == "+") *out << "\tadd rax, rbx\n";
			else if (t.op == "-") *out << "\tsub rax, rbx\n";
			else if (t.op == "*") *out << "\timul rax, rbx\n";
			else if (t.op == "/")
			{
				*out << "\tcqo\n";
				*out << "\tidiv rbx\n";
			}
			else if (t.op == "%")
			{
				*out << "\tcqo\n";
				*out << "\tidiv rbx\n";
				*out << "\tmov rax, rdx\n";
			}
			else if (t.op == "<") { *out << "\tcmp rax, rbx\n"; *out << "\tsetl al\n"; *out << "\tmovzx eax, al\n"; }
			else if (t.op == "<=") { *out << "\tcmp rax, rbx\n"; *out << "\tsetle al\n"; *out << "\tmovzx eax, al\n"; }
			else if (t.op == ">") { *out << "\tcmp rax, rbx\n"; *out << "\tsetg al\n"; *out << "\tmovzx eax, al\n"; }
			else if (t.op == ">=") { *out << "\tcmp rax, rbx\n"; *out << "\tsetge al\n"; *out << "\tmovzx eax, al\n"; }
			else if (t.op == "==") { *out << "\tcmp rax, rbx\n"; *out << "\tsete al\n"; *out << "\tmovzx eax, al\n"; }
			else if (t.op == "!=") { *out << "\tcmp rax, rbx\n"; *out << "\tsetne al\n"; *out << "\tmovzx eax, al\n"; }

			if (tempOffsets.count(i))
				*out << "\tmov [rbp" << tempOffsets[i] << "], rax\n";
		}
		else if (t.op == "-" && t.arg2.empty())
		{
			LoadToRAX(t.arg1);
			*out << "\tneg rax\n";
			if (tempOffsets.count(i))
				*out << "\tmov [rbp" << tempOffsets[i] << "], rax\n";
		}
		else if (t.op == "cast")
		{
			LoadToRAX(t.arg2);
			if (tempOffsets.count(i))
				*out << "\tmov [rbp" << tempOffsets[i] << "], rax\n";
		}
		else if (t.op == "if")
		{
			LoadToRAX(t.arg1);
			*out << "\tcmp rax, 0\n";
			*out << "\tje @@L" << t.arg2 << "\n";
		}
		else if (t.op == "goto")
		{
			*out << "\tjmp @@L" << t.arg1 << "\n";
		}
		else if (t.op == "call")
		{
			Symbol* callee = tree->FindSymbolByAsmName(t.arg1);
			if (callee)
			{
				*out << "\tcall " << callee->asmName << "\n";
				if (tempOffsets.count(i))
					*out << "\tmov [rbp" << tempOffsets[i] << "], rax\n";
			}
		}
		else if (t.op == "index")
		{
			Symbol* arrSym = tree->FindSymbolByAsmName(t.arg1);
			int elemSize = arrSym ? Tree::TypeSize(arrSym->type) : 4;
			LoadEffectiveAddress(t.arg1);
			*out << "\tpush rax\n";
			LoadToRAX(t.arg2);
			*out << "\tmov rbx, " << elemSize << "\n";
			*out << "\timul rax, rbx\n";
			*out << "\tpop rbx\n";
			*out << "\tadd rax, rbx\n";
			indexTriads.insert(i);
			if (tempOffsets.count(i))
				*out << "\tmov [rbp" << tempOffsets[i] << "], rax\n";
		}
	}

	*out << "\tmov rsp, rbp\n";
	*out << "\tpop rbp\n";
	*out << "\tret\n";
	*out << asmFuncName << " ENDP\n\n";
}

int AsmGenerator::ParseIndex(const std::string& s)
{
	if (s.size() >= 3 && s.front() == '(' && s.back() == ')')
	{
		try { return std::stoi(s.substr(1, s.size() - 2)); }
		catch (...) { return -1; }
	}
	return -1;
}

bool AsmGenerator::IsTempIndex(const std::string& operand, int& idx)
{
	idx = ParseIndex(operand);
	return idx >= 0;
}

bool AsmGenerator::IsImmediate(const std::string& s)
{
	char* end;
	long val = strtol(s.c_str(), &end, 10);
	if (*end == '\0') return true;
	val = strtol(s.c_str(), &end, 16);
	return (*end == '\0');
}

Symbol* AsmGenerator::FindSymbolForOperand(const std::string& op)
{
	Symbol* sym = tree->FindSymbolByAsmName(op);
	if (!sym) sym = tree->FindSymbol(op);
	return sym;
}

std::string AsmGenerator::OperandToStr(const std::string& op, bool asAddress)
{
	int idx;
	if (IsTempIndex(op, idx))
	{
		auto it = tempOffsets.find(idx);
		if (it != tempOffsets.end())
		{
			std::stringstream ss;
			ss << "[rbp" << it->second << "]";
			return ss.str();
		}
		return "???";
	}
	if (IsImmediate(op))
		return op;

	Symbol* sym = FindSymbolForOperand(op);
	if (sym)
	{
		if (sym->isLocal)
		{
			std::stringstream ss;
			ss << "[rbp" << sym->offset << "]";
			return ss.str();
		}
		else
		{
			return sym->asmName;
		}
	}
	if (scanner)
		scanner->PrintWarning("OperandToStr: symbol not found for", op);
	return op;
}

void AsmGenerator::LoadToRAX(const std::string& operand)
{
	int idx;
	if (IsTempIndex(operand, idx) && indexTriads.count(idx))
	{
		std::string addr = OperandToStr(operand, true);
		*out << "\tmov rbx, " << addr << "\n";
		*out << "\tmov rax, [rbx]\n";
		return;
	}

	std::string opStr = OperandToStr(operand);
	if (IsImmediate(opStr))
	{
		*out << "\tmov rax, " << opStr << "\n";
		return;
	}

	Symbol* sym = FindSymbolForOperand(operand);
	int size = sym ? Tree::TypeSize(sym->type) : 8;

	if (sym && sym->isLocal)
	{
		if (size == 1)      *out << "\tmovsx rax, byte ptr [rbp" << sym->offset << "]\n";
		else if (size == 2) *out << "\tmovsx rax, word ptr [rbp" << sym->offset << "]\n";
		else if (size == 4) *out << "\tmov eax, [rbp" << sym->offset << "]\n";
		else                *out << "\tmov rax, [rbp" << sym->offset << "]\n";
	}
	else if (sym) // глобальная
	{
		if (size == 1)      *out << "\tmovsx rax, byte ptr [" << sym->asmName << "]\n";
		else if (size == 2) *out << "\tmovsx rax, word ptr [" << sym->asmName << "]\n";
		else if (size == 4) *out << "\tmov eax, [" << sym->asmName << "]\n";
		else                *out << "\tmov rax, [" << sym->asmName << "]\n";
	}
	else
	{
		*out << "\tmov rax, " << opStr << "\n";
	}
}

void AsmGenerator::StoreFromRAX(const std::string& operand)
{
	int idx;
	if (IsTempIndex(operand, idx) && indexTriads.count(idx))
	{
		std::string addr = OperandToStr(operand, true);
		*out << "\tmov rbx, " << addr << "\n";
		*out << "\tmov [rbx], rax\n";
		return;
	}

	std::string opStr = OperandToStr(operand);
	Symbol* sym = FindSymbolForOperand(operand);
	int size = sym ? Tree::TypeSize(sym->type) : 8;

	if (sym && sym->isLocal)
	{
		if (size == 1)      *out << "\tmov [rbp" << sym->offset << "], al\n";
		else if (size == 2) *out << "\tmov [rbp" << sym->offset << "], ax\n";
		else if (size == 4) *out << "\tmov [rbp" << sym->offset << "], eax\n";
		else                *out << "\tmov [rbp" << sym->offset << "], rax\n";
	}
	else if (sym)
	{
		if (size == 1)      *out << "\tmov [" << sym->asmName << "], al\n";
		else if (size == 2) *out << "\tmov [" << sym->asmName << "], ax\n";
		else if (size == 4) *out << "\tmov [" << sym->asmName << "], eax\n";
		else                *out << "\tmov [" << sym->asmName << "], rax\n";
	}
	else
	{
		*out << "\tmov " << opStr << ", rax\n";
	}
}

void AsmGenerator::LoadEffectiveAddress(const std::string& operand)
{
	Symbol* sym = FindSymbolForOperand(operand);
	if (sym && sym->isLocal)
	{
		*out << "\tlea rax, [rbp" << sym->offset << "]\n";
	}
	else if (sym)
	{
		*out << "\tmov rax, offset " << sym->asmName << "\n";
	}
	else
	{
		if (scanner)
			scanner->PrintWarning("LoadEffectiveAddress: symbol not found for", operand);
		*out << "\tmov rax, " << operand << " ; ???\n";
	}
}