; Assembly generated by compiler (x64)

option casemap:none
includelib kernel32.lib
extern ExitProcess : proc

_BSS SEGMENT
	PUBLIC g@01
g@01 DD 1H DUP (?)
_BSS ENDS

_TEXT SEGMENT

main@02 PROC
	push rbp
	mov rbp, rsp
	sub rsp, 48
	mov dword ptr [rbp-4], 10
	mov dword ptr [rbp-8], 20
	mov eax, [rbp-4]
	push rax
	mov rax, 2
	mov rbx, rax
	pop rax
	imul rax, rbx
	mov [rbp-20], rax
	mov rax, [rbp-20]
	mov [rbp-12], eax
	mov eax, [rbp-4]
	push rax
	mov eax, [rbp-8]
	mov rbx, rax
	pop rax
	add rax, rbx
	mov [rbp-28], rax
	mov rax, [rbp-28]
	mov [g@01], eax
	mov eax, [rbp-4]
	push rax
	mov rax, 5
	mov rbx, rax
	pop rax
	cmp rax, rbx
	setg al
	movzx eax, al
	mov [rbp-36], rax
	mov rax, [rbp-36]
	cmp rax, 0
	je @@L11
	mov dword ptr g@01, 1
@@L11:
	mov rsp, rbp
	pop rbp
	ret
main@02 ENDP

_start PROC
	sub rsp, 28h
	call main@02
	mov ecx, eax
	call ExitProcess
_start ENDP

_TEXT ENDS
END _start
