; Assembly generated by compiler (x64)

option casemap:none
includelib kernel32.lib
extern ExitProcess : proc

_BSS SEGMENT
_BSS ENDS

_DATA SEGMENT
	data@01 DD 10, 20, 30, 40
_DATA ENDS

_TEXT SEGMENT

main@02 PROC
	push rbp
	mov rbp, rsp
	sub rsp, 32
	mov rax, offset data@01
	push rax
	mov rax, 2
	mov rbx, 4
	imul rax, rbx
	pop rbx
	add rax, rbx
	mov [rbp-12], rax
	mov rbx, [rbp-12]
	mov rax, [rbx]
	mov [rbp-4], eax
	mov rsp, rbp
	pop rbp
	ret
main@02 ENDP

_start PROC
	sub rsp, 28h
	call main@02
	mov ecx, eax
	call ExitProcess
_start ENDP

_TEXT ENDS
END _start
